apiVersion: v1
items:
- kind: DeploymentConfig
  apiVersion: "v1"
  metadata:
    annotations:
      description: Defines how to deploy the database
      template.alpha.openshift.io/wait-for-ready: 'true'
    name: 'mongodb'
  spec:
    replicas: 1
    selector:
      name: 'mongodb'
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: 'mongodb'
        name: 'mongodb'
      spec:
        containers:
          - env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: mongodb-user
                  name: elasticitems
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-password
                  name: elasticitems
            - name: MONGODB_DATABASE
              value: elasticitems
            - name: MONGODB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-admin-password
                  name: elasticitems
            
            name: mongodb

            ports:
              - containerPort: 27017
            
            livenessProbe:
              failureThreshold: 3
              initialDelaySeconds: 30
              periodSeconds: 10
              successThreshold: 1
              tcpSocket:
                port: 27017
              timeoutSeconds: 1

            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p
                    $MONGODB_PASSWORD --eval="quit()"
              failureThreshold: 3
              initialDelaySeconds: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1

            resources:
              limits:
                memory: '512Mi'
            
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File

            volumeMounts:
              - mountPath: /var/lib/mongodb/data
                name: 'mongodb-data'
        volumes:
          - name: 'mongodb-data'
            persistentVolumeClaim:
              claimName: 'mongodb'
    
    triggers:
      - imageChangeParams:
          automatic: true
          containerNames:
            - mongodb
          from:
            kind: ImageStreamTag
            name: 'mongodb:3.2'
            namespace: 'openshift'
        type: ImageChange
      - type: ConfigChange

- kind: PersistentVolumeClaim
  apiVersion: "v1"
  metadata:
    name: 'mongodb'
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: '1Gi'
        
- kind: Service
  apiVersion: "v1"
  metadata:
    annotations:
      description: Exposes the database server
    name: 'mongodb'
  spec:
    ports:
      - name: 'mongodb'
        protocol: TCP
        port: 27017
        targetPort: 27017
    selector:
      name: 'mongodb'
      
kind: List
metadata: []